export const FETCHED_USERS = 'FETCHED_USERS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const CREATE_USER = 'CREATE_USER'
export const CREATE_TECHNOLOGY = 'CREATE_TECHNOLOGY'
export const FETCHED_TECHNOLOGY = 'FETCHED_TECHNOLOGY'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const LOADING = 'LOADING'
export const FETCHED_PROJECTS = 'FETCHED_PROJECTS'
export const FETCHED_COHORTS = 'FETCHED_COHORTS'
export const CREATE_PROJECT = 'CREATE_PROJECT'
export const SEARCH_TEXT = 'SEARCH_TEXT'

// export {LOGIN, LOGOUT, LOADING, SEARCH_TEXT, FETCHED_USERS, CREATE_USER, SET_CURRENT_USER, FETCHED_PROJECTS, FETCHED_TECHNOLOGY, CREATE_TECHNOLOGY, CREATE_PROJECT,FETCHED_COHORTS}
