const LOADING_USERS = 'LOADING_USERS'
const FETCHED_USERS = 'FETCHED_USERS'
const SET_CURRENT_USER = 'SET_CURRENT_USER'

const LOADING_PROJECTS = 'LOADING_PROJECTS'
const FETCHED_PROJECTS = 'FETCHED_PROJECTS'

const SEARCH_TEXT = 'SEARCH_TEXT'

export {SEARCH_TEXT, LOADING_USERS, FETCHED_USERS, SET_CURRENT_USER, LOADING_PROJECTS, FETCHED_PROJECTS}
