const FETCHED_USERS = 'FETCHED_USERS'
const SET_CURRENT_USER = 'SET_CURRENT_USER'
const CREATE_USER = 'CREATE_USER'
const CREATE_TECHNOLOGY = 'CREATE_TECHNOLOGY'
const FETCHED_TECHNOLOGY = 'FETCHED_TECHNOLOGY'
const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const LOADING = 'LOADING'
const FETCHED_PROJECTS = 'FETCHED_PROJECTS'
const CREATE_PROJECT = 'CREATE_PROJECT'
const SEARCH_TEXT = 'SEARCH_TEXT'

export {LOGIN, LOGOUT, LOADING, SEARCH_TEXT, FETCHED_USERS, CREATE_USER, SET_CURRENT_USER, FETCHED_PROJECTS, FETCHED_TECHNOLOGY, CREATE_TECHNOLOGY, CREATE_PROJECT}
